spring:
  datasource:
    url: jdbc:mysql://39.105.58.186:3306/imchat?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
server:
  port: 8089

# mybatis配置
mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
      map-underscore-to-camel-case: true  #加了这个配置之后就可以直接把下划线分隔的库表字段自动转换为camel格式，不再需要ResultMap
mapper:
  not-empty: false

jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect

